# Generated by Django 6.1 on 2026-08-06 06:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_block_value', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('deduction_amount_per_block', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('tare_weight_per_bag_kg', models.DecimalField(decimal_places=3, default=Decimal('0.500'), max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Setting',
                'verbose_name_plural': 'Business Settings',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('village', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LivePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, unique=True)),
                ('price_per_quintal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('AUTO', 'Fetched Automatically')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity as weighed, before bag-tare deduction.', max_digits=10)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('QUINTAL', 'Quintal (100 KG)')], default='KG', max_length=10)),
                ('num_bags', models.PositiveIntegerField(default=1)),
                ('live_price_per_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tare_weight_used_kg', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=6)),
                ('net_quantity_kg', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.client')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('QUINTAL', 'Quintal (100 KG)')], default='QUINTAL', max_length=10)),
                ('price_per_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.buyer')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('expense_type', models.CharField(choices=[('SHOP_RENT', 'Shop Rent'), ('VEHICLE_RENT', 'Vehicle Rent'), ('LABOUR', 'Labour Cost'), ('LOADING', 'Loading/Unloading'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.purchase')),
                ('related_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.sale')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
